### ISSUE TITLE
Crashes with ValueError: Empty tag name

### ISSUE THREAD

**Issue by ivan** [ludios/wpull#14]
```
ERROR Fatal exception.
Traceback (most recent call last):
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/application/app.py", line 157, in run
    yield from pipeline.process()
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/pipeline/pipeline.py", line 194, in process
    yield from self._process_one_worker()
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/pipeline/pipeline.py", line 215, in _process_one_worker
    task.result()
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/pipeline/pipeline.py", line 119, in process
    item = yield from self.process_one(_worker_id=worker_id)
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/pipeline/pipeline.py", line 103, in process_one
    yield from task.process(item)
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/application/tasks/download.py", line 421, in process
    yield from session.app_session.factory['Processor'].process(session)
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/processor/delegate.py", line 29, in process
    return (yield from processor.process(item_session))
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/processor/web.py", line 91, in process
    return (yield from session.process())
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/processor/web.py", line 185, in process
    yield from self._process_loop()
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/processor/web.py", line 244, in _process_loop
    exit_early, wait_time = yield from self._fetch_one(cast(Request, self._item_session.request))
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/processor/web.py", line 308, in _fetch_one
    action = self._handle_response(request, response)
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/processor/web.py", line 423, in _handle_response
    self._processing_rule.scrape_document(self._item_session)
  File "/home/grab/gs-venv/lib/python3.7/site-packages/libgrabsite/wpull_tweaks.py", line 55, in scrape_document
    super().scrape_document(item_session)
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/processor/rule.py", line 527, in scrape_document
    item_session.url_record.link_type
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/scraper/base.py", line 186, in scrape_info
    scrape_result = scraper.scrape(request, response, link_type)
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/scraper/html.py", line 114, in scrape
    elements, response, base_url, link_contexts
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/scraper/html.py", line 171, in _process_elements
    for link_info in link_infos:
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/scraper/html.py", line 366, in iter_links_element
    for link_info in iterable:
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/scraper/html.py", line 580, in iter_links_plain_element
    for attrib_name, link in self.iter_links_by_attrib(element):
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/scraper/html.py", line 602, in iter_links_by_attrib
    attrib_value = element.attrib.get(attrib_name)
  File "src/lxml/etree.pyx", line 2481, in lxml.etree._Attrib.get
  File "src/lxml/apihelpers.pxi", line 554, in lxml.etree._getAttributeValue
  File "src/lxml/apihelpers.pxi", line 541, in lxml.etree._getNodeAttributeValue
  File "src/lxml/apihelpers.pxi", line 1549, in lxml.etree._getNsTag
  File "src/lxml/apihelpers.pxi", line 1584, in lxml.etree.__getNsTag
ValueError: Empty tag name
CRITICAL Sorry, Wpull unexpectedly crashed.
```

**Comment by ivan** [comment]
Repro with

```
grab-site --1 http://p.im9.eu/mapporn-stereotypes-of-the-netherlands-oc-2000x2255.jpg
```
