### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'resume_reading'

### ISSUE THREAD

**Issue by ivan** [ludios/wpull#3]
819 responses into http://zipcpu.com/about/zipcpu.html:

```
ERROR Fatal exception.
Traceback (most recent call last):
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/app.py", line 127, in run
    yield from self._builder.factory['Engine']()
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/engine.py", line 281, in __call__
    yield from self._run_workers()
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/engine.py", line 70, in _run_workers
    task.result()
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/engine.py", line 149, in _run_worker
    yield from self._process_item(item)
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/engine.py", line 330, in _process_item
    yield from self._process_url_item(url_record)
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/engine.py", line 387, in _process_url_item
    yield from self._processor.process(url_item)
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/processor/delegate.py", line 27, in process
    return (yield from self.web_processor.process(url_item))
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/processor/web.py", line 122, in process
    return (yield from session.process())
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/processor/web.py", line 214, in process
    yield from self._process_loop()
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/processor/web.py", line 273, in _process_loop
    exit_early, wait_time = yield from self._fetch_one(self._request)
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/processor/web.py", line 318, in _fetch_one
    duration_timeout=self._fetch_rule.duration_timeout
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/protocol/http/web.py", line 172, in fetch
    session.read_content(file, duration_timeout=duration_timeout)
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/protocol/http/client.py", line 129, in read_content
    yield from asyncio.wait_for(read_future, timeout=duration_timeout)
  File "/home/grab/.pyenv/versions/3.7.0/lib/python3.7/asyncio/tasks.py", line 412, in wait_for
    return fut.result()
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/protocol/abstract/stream.py", line 15, in wrapper
    return (yield from func(self, *args, **kwargs))
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/protocol/http/stream.py", line 208, in read_body
    yield from self._read_body_by_length(response, file)
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/protocol/http/stream.py", line 280, in _read_body_by_length
    data = yield from self._connection.read(self._read_size)
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/connection.py", line 690, in read
    data = yield from super().read(amount)
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/connection.py", line 553, in read
    name='Read')
  File "/home/grab/gs-venv/lib/python3.7/site-packages/wpull/connection.py", line 587, in run_network_operation
    data = yield from task
  File "/home/grab/.pyenv/versions/3.7.0/lib/python3.7/asyncio/streams.py", line 646, in read
    self._maybe_resume_transport()
  File "/home/grab/.pyenv/versions/3.7.0/lib/python3.7/asyncio/streams.py", line 417, in _maybe_resume_transport
    self._transport.resume_reading()
  File "/home/grab/.pyenv/versions/3.7.0/lib/python3.7/asyncio/sslproto.py", line 345, in resume_reading
    self._ssl_protocol._transport.resume_reading()
AttributeError: 'NoneType' object has no attribute 'resume_reading'
CRITICAL Sorry, Wpull unexpectedly crashed.
CRITICAL Please report this problem to the authors at Wpull's issue tracker so it may be fixed. If you know how to program, maybe help us fix it? Thank you for helping us help you help us all.
```

**Comment by ivan** [comment]
Or within 23 responses on https://forum.digilentinc.com/topic/3735-dds-compiler-60-ip-core-for-audible-sinewave/

**Comment by ivan** [comment]
`asyncio/streams.py:_maybe_resume_transport` is probably buggy (or some other bit of code in the file that fails to set `_paused = False`).

**Comment by ivan** [comment]
Being worked around in https://github.com/ludios/grab-site/commit/9b9682b72209dab1b4e7f149e513175f00a03592#diff-30267b0aeba882fe1003b704fbed5804

**Comment by ivan** [comment]
https://github.com/falconkirtaran/wpull/commit/0c517bab510ff9555bff055b4e1e78a807e0bd90

**Comment by ivan** [comment]
That commit is in our `master` branch now.
