### ISSUE TITLE
Fix/remove wpull.proxy.proxy_test.TestProxySSL

### ISSUE THREAD

**Issue by ivan** [ludios/wpull#8]
```
======================================================================
ERROR: test_basic_requests (wpull.proxy.proxy_test.TestProxySSL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/grab/gs-venv/lib/python3.7/site-packages/tornado/testing.py", line 136, in __call__
    result = self.orig_method(*args, **kwargs)
  File "/home/grab/wpull/thematrix/wpull/testing/async_.py", line 29, in wrapper
    loop=self.event_loop)
  File "/home/grab/.pyenv/versions/3.7.0/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/home/grab/.pyenv/versions/3.7.0/lib/python3.7/asyncio/tasks.py", line 412, in wait_for
    return fut.result()
  File "/home/grab/wpull/thematrix/wpull/proxy/proxy_test.py", line 33, in test_basic_requests
    response = yield from session.start(Request(self.get_url('/')))
  File "/home/grab/wpull/thematrix/wpull/protocol/http/client.py", line 82, in start
    connection = yield from self._acquire_request_connection(request)
  File "/home/grab/wpull/thematrix/wpull/protocol/abstract/client.py", line 80, in _acquire_request_connection
    connection = yield from self._acquire_connection(host, port, use_ssl, tunnel)
  File "/home/grab/wpull/thematrix/wpull/protocol/abstract/client.py", line 90, in _acquire_connection
    tunnel=tunnel)
  File "/home/grab/wpull/thematrix/wpull/proxy/client.py", line 88, in acquire_proxy
    yield from self._establish_tunnel(connection, (host, port))
  File "/home/grab/wpull/thematrix/wpull/proxy/client.py", line 150, in _establish_tunnel
    wpull.string.printable_str(response.reason))
wpull.errors.NetworkError: Proxy does not support CONNECT: 501 CONNECT is intentionally not supported
```

**Comment by HeliosLHC** [comment]
Looks like CONNECT was removed via this commit: https://github.com/ArchiveTeam/ludios_wpull/commit/5613807
